---
apiVersion: batch/v1
kind: Job
metadata:
  name: rpcr-bhon-qoue-uflp
spec:
  template:
    spec:
      containers:
        - name: rpcr-bhon-qoue-uflp
          image: ubuntu
          command: ["bash", "-c", "echo \"Hello\"; exit 1"]
          workingDir: /work
          volumeMounts:
            - name: cwd
              mountPath: /work
      restartPolicy: Never
      securityContext:
        runAsUser: 505
        runAsGroup: 20
      volumes:
        - name: cwd
          hostPath:
            path: /Users/mwvaughn/src/TACC-Cloud/hikar8s
  backoffLimit: 0
